/* Copyright (c) 2022 StuyPulse Robotics. All rights reserved. */
/* This work is licensed under the terms of the MIT license */
/* found in the root directory of this project. */

package com.stuypulse.stuylib.math;

import com.stuypulse.stuylib.util.HashBuilder;

/**
 * A class that is used to store polar coordinates. It's heavily dependant on the vector and angle
 * class.
 *
 * @author Sam Belliveau (sam.belliveau@gmail.com)
 */
public class Polar2D {

    // Configuration for toString() function
    private static final int STRING_SIGFIGS = 5;

    // Internal Variables
    public final double magnitude;
    public final Angle angle;

    /**
     * Create a Polar2D with a magnitude and an angle
     *
     * @param mag magnitude
     * @param ang angle
     */
    public Polar2D(double mag, Angle ang) {
        // Make sure the magnitude is always positive
        if (mag >= 0) {
            magnitude = mag;
            angle = ang;
        } else {
            magnitude = -mag;
            angle = ang.opposite();
        }
    }

    /**
     * Convert a Vector2D into Polar Coordinates
     *
     * @param vec Vector2D to turn into polar coordinates
     */
    public Polar2D(Vector2D vec) {
        this(vec.magnitude(), vec.getAngle());
    }

    /**
     * Get the distance between two Polar2Ds
     *
     * @param other other Polar2D
     * @return the distance between the two Polar2Ds
     */
    public double distance(Polar2D other) {
        final double a = this.magnitude;
        final double b = other.magnitude;
        final Angle t = this.angle.sub(other.angle);
        return Math.sqrt(a * a + b * b - 2.0 * a * b * t.cos());
    }

    /**
     * @return distance from 0, 0
     */
    public double distance() {
        return this.magnitude;
    }

    /**
     * @return magnitude
     */
    public double magnitude() {
        return magnitude;
    }

    /**
     * @return angle
     */
    public Angle getAngle() {
        return angle;
    }

    /**
     * @return Polar Coordinates as a Vector2D
     */
    public Vector2D getVector() {
        return new Vector2D(angle.cos() * magnitude, angle.sin() * magnitude);
    }

    /**
     * @param m scalar to multiply by
     * @return result of multiplication
     */
    public Polar2D mul(double m) {
        return new Polar2D(magnitude * m, angle);
    }

    /**
     * @param d scalar to divide by
     * @return result of division
     */
    public Polar2D div(double d) {
        return new Polar2D(magnitude / d, angle);
    }

    /**
     * @param a angle to rotate by
     * @return result of rotation
     */
    public Polar2D rotate(Angle a) {
        return new Polar2D(magnitude, angle.add(a));
    }

    /**
     * @return Polar2D object with a negated magnitude
     */
    public Polar2D negative() {
        return new Polar2D(-magnitude, angle);
    }

    /**
     * @return normalized polar coordinates
     */
    public Polar2D normalize() {
        return new Polar2D(1, angle);
    }

    /**
     * @param other object to compare to
     * @return both objects are Polar2Ds and they equal eachother
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }

        if (other instanceof Polar2D) {
            Polar2D o = (Polar2D) other;
            return this.magnitude == o.magnitude && this.angle.equals(o.angle);
        }

        return false;
    }

    /**
     * @see com.stuypulse.stuylib.util.HashBuilder#combineHash(int, int)
     * @return hashCode generated by combining the hashes of the magnitude and the angle
     */
    @Override
    public int hashCode() {
        return HashBuilder.combineHash(Double.hashCode(magnitude), angle);
    }

    /**
     * @return String representation of the Polar2D class
     */
    @Override
    public String toString() {
        StringBuilder out = new StringBuilder();
        out.append("Polar2D(");
        out.append(SLMath.round(magnitude, STRING_SIGFIGS));
        out.append(", ");
        out.append(angle);
        out.append(")");
        return out.toString();
    }
}
