package com.stuypulse.stuylib.input;

import com.stuypulse.stuylib.input.gamepads.Logitech;
import com.stuypulse.stuylib.input.gamepads.NullGamepad;
import com.stuypulse.stuylib.input.gamepads.PS4;

import com.stuypulse.stuylib.input.LambdaButton;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;

/**
 * An abstract class for using gamepads with different interfaces.
 * You can implement this class in another file, and then use it
 * with a standard interface.
 * 
 * Any unimplemented buttons will never be triggered, so if
 * a certain controller is missing one, dont worry about it.
 * 
 * In the openPort() command, there is a switch statement
 * that automatically controls which gamepad is selected.
 * Be sure to add any new controllers to this list.
 *
 * If your controller is not in the list, then an error
 * will be reported that tells you the name, type id, and
 * port number of the controller, making adding it to the
 * list easy. Make sure to put the type id in the switch
 * statement and not the port number.
 * 
 * The button type that is used in OI.java is automatically
 * generated by this class, as long as you implement the 
 * getRaw...() function, the get...() function will work.
 * 
 * If you would like to get a button id that is not defined,
 * or an axis id that is not defined, use getRawButton(int id)
 * or getRawAxis(int id). If you want it to return a button
 * for an unimplemented button, type getButton(int id).
 * 
 * To initalize this class, pass in a Joystick or an int
 * set to the port number. This will be the Joystick that
 * the Gamepad class will interact with.
 * 
 * If you do not initialize with a Joystick, everything
 * will still work except for
 * - getRawButton(int id)
 * - getButton(int id)
 * - getRawAxit(int id)
 * which will return either false or 0.0
 * 
 * The difference between the implementations of the 
 * Gamepad class is how it interacts with the underlying
 * Joystick class.
 * 
 * @author Sam (sam.belliveau@gmail.com)
 */

public class Gamepad {

    /**
     * Underlying Joystick Class
     */
    private Joystick mJoy;


    /**
     * Initialize Gamepad without Joystick
     * Joystick will be set to null
     */
    public Gamepad() {
        this.mJoy = null;
    }    
    

    /**
     * Initialize Gamepad with joystick
     * @param joy WPI Joystick
     */
    public Gamepad(Joystick joy) {
        this.mJoy = joy;
    }    
    

    /**
    * Initialize Gamepad with port
    * @param port Joystick port
    */
    public Gamepad(int port) {
        this.mJoy = new Joystick(port);
    }

    /**
     * Create new gamepad and get the 
     * gamepad type from driver station
     * @param port port of new gamepad
     * @return New Gamepad
     */
    public static Gamepad getNewGamepad(int port) {
        switch (DriverStation.getInstance().getJoystickType(port)) {
            case 1:
                return new Logitech.XMode(port);
            case 20:
                return new Logitech.DMode(port);
            case 21:
                return new PS4(port);
            default:// Report debug info if controller is not known
                System.err.println("Unknown Controller [" + (DriverStation.getInstance().getJoystickName(port)) + "]");
                System.err.println("\tType: " + (DriverStation.getInstance().getJoystickType(port)));
                System.err.println("\tPort: " + (port));
                
                // Return gamepad that always returns false for 
                // every button, as if controller is not connected
                return new NullGamepad(port);
        }
    }


    /********************************/
    /*** JOYSTICK GETTERS/SETTERS ***/
    /********************************/

    /**
     * Checks if Gamepad has a Joystick
     * @return if Gamepad has a Joystick
     */
    public final boolean hasJoystick() {
        return getJoystick() != null;
    }

    /**
     * Get underlying joystick
     * @return Underlying joystick
     */
    public final Joystick getJoystick() {
        return this.mJoy;
    }

    /**
     * Get button from underlying joystick
     * @param button Joystick button id
     * @return the value of the button
     */
    public final boolean getRawButton(int button) {
        if(!hasJoystick()) { return false; }
        return getJoystick().getRawButton(button);
    }

    /**
     * Get button from underlying joystick
     * @param button Joystick button id
     * @return the value of the button
     */
    public final Button getButton(int button) {
        return new LambdaButton(() -> getRawButton(button));
    }

    /**
     * Get axis from underlying joystick
     * @param axis Joystick axis id
     * @return the value of the axis
     */
    public final double getRawAxis(int axis) {
        if(!hasJoystick()) { return 0.0; }
        return getJoystick().getRawAxis(axis);
    }


    /**************************/
    /*** LEFT CONTROL STICK ***/
    /**************************/

    /**
     * The left analog stick x-axis.
     * @return value of left analog x-axis
     */
    public double getLeftX() { return 0.0; }

    /**
     * The left analog stick y-axis.
     * @return value of left analog y-axis (pushing stick up is positive)
     */
    public double getLeftY() { return 0.0; }


    /***************************/
    /*** RIGHT CONTROL STICK ***/
    /***************************/

    /**
     * The right analog stick x-axis.
     * @return value of right analog x-axis
     */
    public double getRightX() { return 0.0; }


    /**
     * The right analog stick y-axis.
     * @return value of right analog y-axis (pushing stick up is positive)
     */
    public double getRightY() { return 0.0; }
    

    /**********************/
    /*** D-PAD CONTROLS ***/
    /**********************/

    /**
     * The upper d-pad button.
     * @return if upper d-pad button is pressed
     */
    public boolean getRawDPadUp() { return false; }
    public final Button getDPadUp() {
        return new LambdaButton(() -> this.getRawDPadUp());
    }
    
    /**
     * The lower d-pad button.
     * @return if lower d-pad button is pressed
     */
    public boolean getRawDPadDown() { return false; }
    public final Button getDPadDown() {
        return new LambdaButton(() -> this.getRawDPadDown());
    }
    
    /**
     * The left d-pad button.
     * @return if left d-pad button is pressed
     */
    public boolean getRawDPadLeft() { return false; }
    public final Button getDPadLeft() {
        return new LambdaButton(() -> this.getRawDPadLeft());
    }
    

    /**
     * The right d-pad button.
     * @return if right d-pad button is pressed
     */
    public boolean getRawDPadRight() { return false; }
    public final Button getDPadRight() {
        return new LambdaButton(() -> this.getRawDPadRight());
    }


    /*******************/
    /*** LEFT BUMPER ***/
    /*******************/
    public boolean getRawLeftBumper() { return false; }
    public final Button getLeftBumper() {
        return new LambdaButton(() -> this.getRawLeftBumper());
    }


    /********************/
    /*** RIGHT BUMPER ***/
    /********************/
    public boolean getRawRightBumper() { return false; }
    public final Button getRightBumper() {
        return new LambdaButton(() -> this.getRawRightBumper());
    }


    /******************************/
    /*** TRIGGER AXIS THRESHOLD ***/
    /******************************/
    protected static final double TRIGGER_AXIS_THRESHOLD = 2.0 / 16.0;


    /********************/
    /*** LEFT TRIGGER ***/
    /********************/
    public double getRawLeftTriggerAxis() { return 0.0; }

    public boolean getRawLeftTrigger() {
        return getRawLeftTriggerAxis() > TRIGGER_AXIS_THRESHOLD;
    }

    public final Button getLeftTrigger() { 
        return new LambdaButton(() -> this.getRawLeftTrigger());
    } 


    /*********************/
    /*** RIGHT TRIGGER ***/
    /*********************/
    public double getRawRightTriggerAxis() { return 0; }

    public boolean getRawRightTrigger() {
        return getRawRightTriggerAxis() > TRIGGER_AXIS_THRESHOLD;
    }

    public final Button getRightTrigger() { 
        return new LambdaButton(() -> this.getRawRightTrigger());
    } 


    /*******************/
    /*** LEFT BUTTON ***/
    /*******************/
    public boolean getRawLeftButton() { return false; }

    public final Button getLeftButton() { 
        return new LambdaButton(() -> this.getRawLeftButton());
    } 


    /********************/
    /*** RIGHT BUTTON ***/
    /********************/
    public boolean getRawRightButton() { return false; }

    public final Button getRightButton() { 
        return new LambdaButton(() -> this.getRawRightButton());
    } 


    /******************/
    /*** TOP BUTTON ***/
    /******************/
    public boolean getRawTopButton() { return false; }

    public final Button getTopButton() { 
        return new LambdaButton(() -> this.getRawTopButton());
    } 


    /*********************/
    /*** BOTTOM BUTTON ***/
    /*********************/
    public boolean getRawBottomButton() { return false; }

    public final Button getBottomButton() { 
        return new LambdaButton(() -> this.getRawBottomButton());
    } 


    /*********************/
    /*** SELECT BUTTON ***/
    /*********************/
    public boolean getRawSelectButton() { return false; }

    public final Button getSelectButton() { 
        return new LambdaButton(() -> this.getRawSelectButton());
    } 


    /********************/
    /*** START BUTTON ***/
    /********************/
    public boolean getRawStartButton() { return false; }

    public final Button getStartButton() { 
        return new LambdaButton(() -> this.getRawStartButton());
    } 


    /**************************/
    /*** LEFT ANALOG BUTTON ***/
    /**************************/
    public boolean getRawLeftAnalogButton() { return false; }

    public final Button getLeftAnalogButton() { 
        return new LambdaButton(() -> this.getRawLeftAnalogButton());
    } 


    /***************************/
    /*** RIGHT ANALOG BUTTON ***/
    /***************************/
    public boolean getRawRightAnalogButton() { return false; }

    public final Button getRightAnalogButton() { 
        return new LambdaButton(() -> this.getRawRightAnalogButton());
    } 


    /*********************/
    /*** OPTION BUTTON ***/
    /*********************/
    public boolean getRawOptionButton() { return false; }

    public final Button getOptionButton() { 
        return new LambdaButton(() -> this.getRawOptionButton());
    } 

    /**************/
    /*** RUMBLE ***/
    /**************/
    public void rumble(double intensity) {}
}
