
name: Build StuyLib to Jar File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for build tool
      run: chmod +x ./build_release.sh
    - name: Build with build tool / generate jar file
      run: ./build_release.sh TEST.BUILD
