name: Deploy Release

on:
  release:
    type: create

env:
  JAVA_VERSION: 1.11
  GRADLE_VERSION: 7.2

jobs:
  deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
        
    - name: Spotless Check - Gradle ${{ env.GRADLE_VERSION }}
      uses: gradle/gradle-build-action@v2.3.0-beta.1
      with:
        gradle-version: ${{ env.GRADLE_VERSION }} 
        arguments: spotlessApply -Pversion=${{ github.event.release.tag_name }}
        
    - name: Build Javadocs - Gradle ${{ env.GRADLE_VERSION }}
      uses: gradle/gradle-build-action@v2.3.0-beta.1
      with:
        arguments: javadoc -Pversion=${{ github.event.release.tag_name }}
        
    - name: Build - Gradle ${{ env.GRADLE_VERSION }}
      uses: gradle/gradle-build-action@v2.3.0-beta.1
      with:
        arguments: build -Pversion=${{ github.event.release.tag_name }}

    - name: Upload Assets to Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ./build./libs/*.jar
        repo-token: ${{ secrets.GITHUB_TOKEN }}
